local_balenaos:
  app-name: local-app
  build-triggers:
    - Dockerfile: e400611e0bc4b4de7d228568fa1b3379fc9b87c7bb940bf2b22c078688251d83
  environment: []
uuid: 48840fb90a45c68ae6496e848f95a2ba
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
