local_balenaos:
  app-name: local-app
  build-triggers:
    - Dockerfile: b50548c65f1b4f3bd8a015590a635fbc68106f15f8ddc42554187fbddd689da2
  environment: []
uuid: 48840fb90a45c68ae6496e848f95a2ba
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
